version: '3.7'

services:

  limiter:
    build:
      context: .
    depends_on:
      - redis-service-rate-limiter
    ports:
      - 3000:3000
    environment:
      - RATELIMITER_BACKEND_URL=https://your.server:8000
      - RATELIMITER_REDIS_URL=redis://redis-service-rate-limiter:6379
      - RATELIMITER_WINDOW_MS=60000
      - RATELIMITER_MAX=100
      - RATELIMITER_FRONTEND_PORT=3000
      - RATELIMITER_VERBS=["GET","POST"]

  redis-service-rate-limiter:
    container_name: redis-service-rate-limiter
    image: redis
    restart: always
    ports:
      - 6379

