version: '3.7'

services:

  limiter:
    container_name: limiter
    build:
      context: .
    depends_on:
      - redis
    ports:
      - 3001:3000
  
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379

